[build-system]
build-backend = "uv_build"
requires = [ "uv-build>=0.11.2,<0.12" ]

[project]
name = "cf-cm-tree"
version = "1.0.0"
description = "Generic and light-weight package to assist CF-compliant dataset creation"
readme = "README.md"
authors = [ { name = "eodc", email = "claudio.schein-navacchi@eodc.eu" } ]
requires-python = ">=3.10"
classifiers = [
  "Intended Audience :: Science/Research",
  "Natural Language :: English",
  "Operating System :: POSIX",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Topic :: Scientific/Engineering",
  "Topic :: Scientific/Engineering :: GIS",
  "Topic :: Software Development :: Libraries",
]
dependencies = [ "pydantic", "xarray" ]
[project.urls]
Repository = "https://github.com/eodcgmbh/cf-cm-tree"

[dependency-groups]
test = [ "pytest", "pytest-cov" ]
trunk = []

[tool.black]
line-length = 88
target-version = [ "py312" ]
skip-string-normalization = false

[tool.ruff.format]
# Same as Black.
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"
[tool.ruff.lint]
select = [ "ALL" ]
ignore = [
  "COM812",  # missing-trailing-comma (may conflict with ruff formatter)
  "D203",    # incorrect-blank-line-before-class (conflicts with D211)
  "D213",    # multi-line-summary-second-line (conflicts with D212)
  "PLR0913",
  "PLC0415", # allow imports to be within functions for executables
  "ANN401",  # allow Any
]
exclude = [ "docs/*" ]
fixable = [ "ALL" ]
unfixable = []
[tool.ruff.lint.per-file-ignores]
"__init__.py" = [ "E402" ]
"**/{tests}/*" = [ "E402", "ANN201", "D", "INP001", "S101" ]

[tool.pyproject-fmt]
table_format = "long"
collapse_tables = [ "project.authors" ]

[tool.pytest.ini_options]
addopts = "--cov=cf_cm_tree --cov-report term-missing -rsx --verbose --color=yes"
markers = [ "warp_installed" ]

[tool.coverage.run]
relative_files = true

[tool.ty.rules]
possibly-missing-attribute = "ignore"
unresolved-attribute = "ignore"
invalid-method-override = "ignore"
[tool.ty.src]
exclude = [ "docs/*" ]
