[project]
authors = [{ name = "EODC", email = "claudio.schein-navacchi@eodc.eu" }]
name = "eodc_cf"
dynamic = ["version"]
description = "Generic and light-weight package to assist CF-compliant dataset creation"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pydantic",
    "xarray"
]
classifiers = [
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: GIS",
    "Topic :: Software Development :: Libraries",
    "Programming Language :: Python :: 3.12",
    "Operating System :: POSIX",
    "Natural Language :: English",
]
[project.urls]
Repository = "https://github.com/eodcgmbh/eodc-cf"

[build-system]
requires = ["setuptools", "pydantic"]
build-backend = "setuptools.build_meta"

[dependency-groups]
test = [
    "pytest",
    "pytest-cov"
]
trunk = []

[tool.black]
line-length = 88
target-version = ["py312"]
skip-string-normalization = false

[tool.ruff]
line-length = 88
target-version = "py312"

lint.select = ["E", "F", "I", "B", "UP", "N"]
lint.ignore = [
  "E501", # ignore line length warnings because Black handles that
]

# Optional: autofix simple issues when running `ruff check --fix`
fix = true

[tool.ruff.lint.isort]
known-first-party = ["eodc_cf"]
combine-as-imports = true